Return-Path: <linux-nfs-owner@vger.kernel.org>
X-Original-To: lists+linux-nfs@lfdr.de
Delivered-To: lists+linux-nfs@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id A665B627BEC
	for <lists+linux-nfs@lfdr.de>; Mon, 14 Nov 2022 12:18:04 +0100 (CET)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S230079AbiKNLRd (ORCPT <rfc822;lists+linux-nfs@lfdr.de>);
        Mon, 14 Nov 2022 06:17:33 -0500
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:41856 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S236800AbiKNLQk (ORCPT
        <rfc822;linux-nfs@vger.kernel.org>); Mon, 14 Nov 2022 06:16:40 -0500
Received: from mail-ej1-x62c.google.com (mail-ej1-x62c.google.com [IPv6:2a00:1450:4864:20::62c])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id B4D63B84E
        for <linux-nfs@vger.kernel.org>; Mon, 14 Nov 2022 03:13:41 -0800 (PST)
Received: by mail-ej1-x62c.google.com with SMTP id y14so27417968ejd.9
        for <linux-nfs@vger.kernel.org>; Mon, 14 Nov 2022 03:13:41 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=googlemail.com; s=20210112;
        h=message-id:date:subject:cc:to:from:from:to:cc:subject:date
         :message-id:reply-to;
        bh=E9S9Sru0Ne2Q+DTJ/+/XcQvOZOXdre75IkBEdH/mDks=;
        b=Rcs+vxNL/6YbQ873RuKvAijDo4YhzIxI7WhmTZf1eeYJyBVkWG0Dt6Cq17N57ZB4mg
         KRsxnyOZ0iBHv4LaAOfXIyfkpLJHI3RpCviC1RtENc5ZQGWK/k0IJ3vqDPKo0TgDpn1A
         e70bXEde974DKPqfyDmjxPDf5NQjwbwzuUu9r8VBPCrvjHoJtA6B2lm2nTwUbwPq+lsM
         RnaNBQRdHoOgkRm7gJYv3+ANIoOsBLkWVsl07hnp/CoipPvlq3Z5+h+99Vndh4slOMPF
         yApxj1HsuxAP6R8qTPgc3PrQFX2UHamlUzr3lwxs/Cmw1jEyisqCdFjdXhuefq4LoD4j
         m3KQ==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20210112;
        h=message-id:date:subject:cc:to:from:x-gm-message-state:from:to:cc
         :subject:date:message-id:reply-to;
        bh=E9S9Sru0Ne2Q+DTJ/+/XcQvOZOXdre75IkBEdH/mDks=;
        b=JrgLgdnq1HuRJaXoKimwp02TDdk9zjBvJgbgRpA0G43j/M/Bc5YDscG4Gn84O0CIrM
         PRAOzAEBDxnM87fC3NysXsk5zQGu83UXhMOcEzBfvs5zkHSgTn+eW43tZzOEBwtqcw9N
         872MgcCF6kwSOAbeJAtnj3gWnZun18PgNixt14EE1n04KY2klprlgUbtlc22DNKJSiNR
         ofUN2NmMYP4ijxikJT1l9ly+8XMrXJZHfYglwxLcnf/Qt4OE9Fbaxs4yn6i8qwinZ4PV
         h93CTgASxGHLcRdZH8RnnH46c075k9flxotZ4aDgfdKUjzNujj68MdnPY3Xi1IZsEEkY
         JX2w==
X-Gm-Message-State: ANoB5plhGS4deBqfeugds+Zf9hXC2oG9z9Ouf/t0qLt5jsN6Y0TRomF2
        3mv0kb9pnvqv5Ql1tnEZ9WLagRuORYM=
X-Google-Smtp-Source: AA0mqf7UmuRJwKkHI9IunR+Nm68utuvm0xN9PENN8b4R1B7B0k097yurBYU9298jILErxGkJyhJ5xQ==
X-Received: by 2002:a17:906:f915:b0:78d:c7fd:f755 with SMTP id lc21-20020a170906f91500b0078dc7fdf755mr10204832ejb.702.1668424419845;
        Mon, 14 Nov 2022 03:13:39 -0800 (PST)
Received: from development1.visionsystems.de (mail.visionsystems.de. [213.209.99.202])
        by smtp.gmail.com with ESMTPSA id la8-20020a170907780800b00781b589a1afsm4052059ejc.159.2022.11.14.03.13.38
        (version=TLS1_2 cipher=ECDHE-ECDSA-AES128-GCM-SHA256 bits=128/128);
        Mon, 14 Nov 2022 03:13:39 -0800 (PST)
From:   yegorslists@googlemail.com
To:     linux-nfs@vger.kernel.org
Cc:     Yegor Yefremov <yegorslists@googlemail.com>
Subject: [PATCH] .gitignore: ignore ctags generated file
Date:   Mon, 14 Nov 2022 12:13:33 +0100
Message-Id: <20221114111333.10838-1-yegorslists@googlemail.com>
X-Mailer: git-send-email 2.17.0
X-Spam-Status: No, score=-2.1 required=5.0 tests=BAYES_00,DKIM_SIGNED,
        DKIM_VALID,DKIM_VALID_AU,DKIM_VALID_EF,FREEMAIL_FROM,
        RCVD_IN_DNSWL_NONE,SPF_HELO_NONE,SPF_PASS autolearn=ham
        autolearn_force=no version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <linux-nfs.vger.kernel.org>
X-Mailing-List: linux-nfs@vger.kernel.org

From: Yegor Yefremov <yegorslists@googlemail.com>

---
 .gitignore | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/.gitignore b/.gitignore
index df791a83..682153d5 100644
--- a/.gitignore
+++ b/.gitignore
@@ -86,3 +86,5 @@ systemd/rpc-gssd.service
 cscope.*
 # generic editor backup et al
 *~
+# file generated by ctags
+tags
-- 
2.17.0

